# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ritchie_pb2 as ritchie__pb2


class RitchieStub(object):
    """The Formula service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ritchie = channel.unary_unary(
                '/ritchie.Ritchie/Ritchie',
                request_serializer=ritchie__pb2.RitchieRequest.SerializeToString,
                response_deserializer=ritchie__pb2.RitchieReply.FromString,
                )


class RitchieServicer(object):
    """The Formula service definition.
    """

    def Ritchie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RitchieServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ritchie': grpc.unary_unary_rpc_method_handler(
                    servicer.Ritchie,
                    request_deserializer=ritchie__pb2.RitchieRequest.FromString,
                    response_serializer=ritchie__pb2.RitchieReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ritchie.Ritchie', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ritchie(object):
    """The Formula service definition.
    """

    @staticmethod
    def Ritchie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ritchie.Ritchie/Ritchie',
            ritchie__pb2.RitchieRequest.SerializeToString,
            ritchie__pb2.RitchieReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
