# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ritchie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ritchie.proto',
  package='ritchie',
  syntax='proto3',
  serialized_options=b'\n\030io.grpc.examples.ritchieB\014RitchieProtoP\001\242\002\003RIT',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rritchie.proto\x12\x07ritchie\"!\n\x0eRitchieRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x1f\n\x0cRitchieReply\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\x07Ritchie\x12;\n\x07Ritchie\x12\x17.ritchie.RitchieRequest\x1a\x15.ritchie.RitchieReply\"\x00\x42\x30\n\x18io.grpc.examples.ritchieB\x0cRitchieProtoP\x01\xa2\x02\x03RITb\x06proto3'
)




_RITCHIEREQUEST = _descriptor.Descriptor(
  name='RitchieRequest',
  full_name='ritchie.RitchieRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='ritchie.RitchieRequest.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_RITCHIEREPLY = _descriptor.Descriptor(
  name='RitchieReply',
  full_name='ritchie.RitchieReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ritchie.RitchieReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['RitchieRequest'] = _RITCHIEREQUEST
DESCRIPTOR.message_types_by_name['RitchieReply'] = _RITCHIEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RitchieRequest = _reflection.GeneratedProtocolMessageType('RitchieRequest', (_message.Message,), {
  'DESCRIPTOR' : _RITCHIEREQUEST,
  '__module__' : 'ritchie_pb2'
  # @@protoc_insertion_point(class_scope:ritchie.RitchieRequest)
  })
_sym_db.RegisterMessage(RitchieRequest)

RitchieReply = _reflection.GeneratedProtocolMessageType('RitchieReply', (_message.Message,), {
  'DESCRIPTOR' : _RITCHIEREPLY,
  '__module__' : 'ritchie_pb2'
  # @@protoc_insertion_point(class_scope:ritchie.RitchieReply)
  })
_sym_db.RegisterMessage(RitchieReply)


DESCRIPTOR._options = None

_RITCHIE = _descriptor.ServiceDescriptor(
  name='Ritchie',
  full_name='ritchie.Ritchie',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=94,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ritchie',
    full_name='ritchie.Ritchie.Ritchie',
    index=0,
    containing_service=None,
    input_type=_RITCHIEREQUEST,
    output_type=_RITCHIEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RITCHIE)

DESCRIPTOR.services_by_name['Ritchie'] = _RITCHIE

# @@protoc_insertion_point(module_scope)
